---
title: "VARITY"
author: "Bilin"
date: "`r Sys.Date()`"
output: pdf_document
---

```{r}
library(ggplot2)
library(dplyr)
library(stringr)
library(ggpubr)
library(tidyr)
library(patchwork)
```

```{r}
aa <- list("A" = "Ala", "R" = "Arg", "N" = "Asn", "D" = "Asp", "C" = "Cys", 
           "E" = "Glu", "Q" = "Gln", "G" = "Gly", "H" = "His", "I" = "Ile",
           "L" = "Leu", "K" = "Lys", "M" = "Met", "F" = "Phe", "P" = "Pro",
           "S" = "Ser", "T" = "Thr", "W" = "Trp", "Y" = "Tyr", "V" = "Val")
```

```{r}
new <- read.csv(file = "../data/select_t1_simple_aa.csv", skip = 16) %>% 
  select(hgvs_pro, score, se) %>% 
  mutate(last3=substr(hgvs_pro, nchar(hgvs_pro)-2, nchar(hgvs_pro))) %>% 
  group_by(last3) %>% 
  mutate(group = ifelse(grepl("=", last3), "synonymous", ifelse(grepl("Ter$", last3), "nonsense", "missense"))) %>% 
  filter(group == 'missense')
```

```{r}
VARITY_R <- read.csv(file = "../data/UBE2I[P63279]_1-158_VARITY_ER_20230605191253505421.csv") %>% 
  select(aa_pos, aa_ref, aa_alt, VARITY_R) %>% 
  drop_na() %>% 
  mutate(hgvs_pro = paste("p.", aa[aa_ref], aa_pos, aa[aa_alt], sep = ''))
```

```{r}
match_df <- left_join(new, VARITY_R, join_by("hgvs_pro")) %>% 
  drop_na() %>% 
  rename(fitness.score=score, LOD.for.pathogenicity=VARITY_R) %>% 
  mutate(wildtype = substr(hgvs_pro, 3, 5))
```

```{r}
new_facet <- ggplot(match_df, aes(x = fitness.score, y = LOD.for.pathogenicity)) + 
  geom_point(aes(color=wildtype, alpha = 0.9)) +
  facet_wrap(~ wildtype, scales = "fixed") +
  geom_smooth(method = "lm", aes(color = wildtype))+
  stat_cor(method= "spearman", label.x = -0.3, label.y = 0.35, cor.coef.name = "rho", aes(label = ..r.label..)) +
  geom_rug(aes(color=wildtype)) +
  theme_bw() +
  theme(axis.text.x = element_text(angle = 45), legend.position = "none")

# ggsave(filename = "/Users/admin/Desktop/UBE2I/VARITY_Tileseq/output/facet_plot.jpg", dpi = 600)
```

```{r}
new_whole <- ggplot(match_df, aes(x = fitness.score, y = LOD.for.pathogenicity)) + 
  geom_point(aes(color=wildtype, alpha=0.9)) +
  geom_smooth(method = "lm") +
  stat_cor(method= "spearman", label.x = -0.2, label.y = 0.3, cor.coef.name = "rho",aes(label = ..r.label..)) +
  geom_rug(aes(color=wildtype))+
  theme_bw()+
  theme(legend.position = "bottom") +
  theme(legend.key.size = unit(0.5, "cm"))

# ggsave(filename = "/Users/admin/Desktop/UBE2I/VARITY_Tileseq/output/plot.jpg", dpi = 600)
```

```{r}
old <- read.csv(file = "../data/urn_mavedb_00000001-a-3_scores.csv") %>% 
  select(hgvs_pro, score, se) %>% 
  distinct() %>% 
  mutate(last3=substr(hgvs_pro, nchar(hgvs_pro)-2, nchar(hgvs_pro))) %>% 
  group_by(last3) %>% 
  mutate(group = ifelse(grepl("=", last3), "synonymous", ifelse(grepl("Ter$", last3), "nonsense", "missense"))) %>% 
  filter(group == "missense")
```

```{r}
match_old <- left_join(old, VARITY_R, join_by("hgvs_pro")) %>% 
  rename(fitness.score=score, LOD.for.pathogenicity=VARITY_R) %>% 
  mutate(wildtype=substr(hgvs_pro, 3, 5)) %>% 
  drop_na()
```

```{r}
old_facet <- ggplot(match_old, aes(x = fitness.score, y = LOD.for.pathogenicity)) + 
  geom_point(aes(color=wildtype, alpha = 0.9)) +
  facet_wrap(~ wildtype, scales = "fixed") +
  geom_smooth(method = "lm", aes(color = wildtype))+
  stat_cor(method= "spearman", label.x = -0.3, label.y = 0.35, cor.coef.name = "rho", aes(label = ..r.label..)) +
  geom_rug(aes(color=wildtype)) +
  theme_bw() +
  theme(axis.text.x = element_text(angle = 45), legend.position = "none")

# ggsave(filename = "../output/facet_old_VARITY.jpg", dpi = 600)
```

```{r}
old_whole <- ggplot(match_old, aes(x = fitness.score, y = LOD.for.pathogenicity)) + 
  geom_point(aes(color=wildtype, alpha=0.9)) +
  geom_smooth(method = "lm") +
  stat_cor(method= "spearman", label.x = -0.2, label.y = 0.3, cor.coef.name = "rho",aes(label = ..r.label..)) +
  geom_rug(aes(color=wildtype))+
  theme_bw()+
  theme(legend.position = "bottom") +
  theme(legend.key.size = unit(0.5, "cm"))

# ggsave(filename = "/Users/admin/Desktop/UBE2I/VARITY_Tileseq/output/plot_old.jpg", dpi = 600)
```

```{r}
old_facet + old_whole + new_facet + new_whole
# ggsave(filename = "../output/VARITY_new_old.jpg", dpi = 600, width = 12, height = 12)
```

